(function(){var O=function(){function g(a,b){var c;if("ZERO_OUT"===b)return a.setSeconds(0),a;if("string"===typeof b&&/^\d+$/.test(b))c=parseInt(b,10);else if("number"===typeof b)c=b;else return;if(0>c||59<c)return;a.setSeconds(c);return a}function n(a){var b=a.getSeconds()+1;return g(a,59<b?0:b)}function A(a){var b=a.getSeconds()-1;return g(a,0>b?59:b)}function l(a,b){var c;if("ZERO_OUT"===b)return a.setMinutes(0),a;if("string"===typeof b&&/^\d+$/.test(b))c=parseInt(b,10);else if("number"===typeof b)c=
b;else return;if(0>c||59<c)return;a.setMinutes(c);return a}function q(a){var b=a.getMinutes()+1;return l(a,59<b?0:b)}function u(a){var b=a.getMinutes()-1;return l(a,0>b?59:b)}function k(a,b){var c,e=11<a.getHours()?"PM":"AM";if("ZERO_OUT"===b)return a.setHours("AM"===e?0:12),a;if("string"===typeof b&&/^\d+$/.test(b))c=parseInt(b,10);else if("number"===typeof b)c=b;else return;0===c&&(c=1);if(1>c||12<c)return;12===c&&"AM"===e&&(c=0);12!==c&&"PM"===e&&(c+=12);a.setHours(c);return a}function r(a){var b=
a.getHours()+1;return k(a,23<b?0:b)}function x(a){var b=a.getHours()-1;return k(a,0>b?23:b)}function d(a,b){var c;if("ZERO_OUT"===b)return a.setHours(0),a;if("string"===typeof b&&/^\d+$/.test(b))c=parseInt(b,10);else if("number"===typeof b)c=b;else return;if(0>c||23<c)return;a.getHours()===c+1?(a.setHours(c),a.getHours()!==c&&a.setHours(c-1)):a.setHours(c);return a}function D(a,b){var c;if("ZERO_OUT"===b)return a.setDate(1),a;if("string"===typeof b&&/\d{1,2}.*$/.test(b))c=parseInt(b,10);else if("number"===
typeof b)c=b;else return;0===c&&(c=1);if(1>c||c>F(a))return;a.setDate(c);return a}function h(a){var b=a.getDate()+1;return D(a,b>F(a)?1:b)}function v(a){var b=a.getDate()-1;return D(a,0>b?F(a):b)}function m(a,b){var c;if("ZERO_OUT"===b)return m(a,0);if("number"===typeof b)c=b;else if("string"!==typeof b||!e.some(function(a){if((new RegExp("^"+b+".*$","i")).test(a))return c=e.indexOf(a),!0}))return;if(0>c||6<c)return;a.setDate(a.getDate()-(a.getDay()-c));return a}function I(a){var b=a.getDay()+1;return m(a,
6<b?0:b)}function f(a){var b=a.getDay()-1;return m(a,0>b?6:b)}function E(a,b){var c;if("ZERO_OUT"===b)return a.setMonth(0),a;if("string"===typeof b&&/^\d+$/.test(b))c=parseInt(b,10);else if("number"===typeof b)c=b;else return;0===c&&(c=1);if(1>c||12<c)return;a.setMonth(c-1);return a}function w(a){var b=a.getMonth()+2;return m(a,12<b?1:b)}function B(a){var b=a.getMonth();return m(a,1>b?12:b)}function G(a,b){var c;if("ZERO_OUT"===b)return a.setMonth(0),a;if("string"!==typeof b||!C.some(function(a){if((new RegExp("^"+
b+".*$","i")).test(a))return c=C.indexOf(a)+1,!0})||1>c||12<c)return;a.setMonth(c-1);return a}function z(a,b){var c;if("ZERO_OUT"===b)return a.setFullYear(0),a;if("string"===typeof b&&/^\d+$/.test(b))c=parseInt(b,10);else if("number"===typeof b)c=b;else return;a.setFullYear(c);return a}function p(a,b){var c=a.getHours();if("ZERO_OUT"===b)return a;if("string"===typeof b&&/^am?$/i.test(b))c-=12;else if("string"===typeof b&&/^pm?$/i.test(b))c+=12;else return;if(0>c||23<c)return a;a.setHours(c);return a}
function J(a){var b=a.getHours()+12;return k(a,23<b?b-24:b)}function t(a){var b=a.getHours()-12;return k(a,0>b?b+24:b)}function F(a){return(new Date(a.getFullYear(),a.getMonth()+1,0)).getDate()}function M(a){a=a.getMonth();return 0===a?2:1===a?1:2===a?3:3===a?2:4===a||5===a||6===a?3:7===a?2:1}function K(a){return 11<a.getHours()?13<a.getHours()?1:2:1<a.getHours()?1:2}function H(a,b){var c=-a.getTimezoneOffset();return(0<=c?"+":"-")+y(c/60)+(b?":":"")+y(c%60)}function y(a){for(a=Math.abs(a).toString();2>
a.length;)a="0"+a;return a}function N(a){return 0===a?12:12<a?a-12:a}var C="January February March April May June July August September October November December".split(" "),e="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" ");return[{code:"YYYY",a:"\\d{4,4}",b:function(a){return a.getFullYear().toString()},f:function(a){return z(a,a.getFullYear()+1)},c:function(a){return z(a,a.getFullYear()-1)},set:function(a,b){return z(a,b)},g:function(){return 4}},{code:"YY",a:"\\d{2,2}",b:function(a){return a.getFullYear().toString().slice(-2)},
f:function(a){return z(a,a.getFullYear()+1)},c:function(a){return z(a,a.getFullYear()-1)},set:function(a,b){var c;a:{c=a;var e=100*Math.floor(c.getFullYear()/100),t;if("ZERO_OUT"===b)c.setFullYear(e);else{if("string"===typeof b&&/^\d+$/.test(b))t=parseInt(b,10);else if("number"===typeof b)t=b;else{c=void 0;break a}c.setFullYear(e+t)}}return c},g:function(){return 2}},{code:"MMMM",a:"(("+C.join(")|(")+"))",b:function(a){return C[a.getMonth()]},f:function(a){return w(a)},c:function(a){return B(a)},
set:function(a,b){return G(a,b)},g:function(a){return M(a)}},{code:"MMM",a:"(("+C.map(function(a){return a.slice(0,3)}).join(")|(")+"))",b:function(a){return C[a.getMonth()].slice(0,3)},f:function(a){return w(a)},c:function(a){return B(a)},set:function(a,b){return G(a,b)},g:function(a){return M(a)}},{code:"MM",a:"\\d{2,2}",b:function(a){return y(a.getMonth()+1)},f:function(a){return w(a)},c:function(a){return B(a)},set:function(a,b){return E(a,b)},g:function(a){return 0<a.getMonth()?1:2}},{code:"M",
a:"\\d{1,2}",b:function(a){return(a.getMonth()+1).toString()},f:function(a){return w(a)},c:function(a){return B(a)},set:function(a,b){return E(a,b)},g:function(a){return 0<a.getMonth()?1:2}},{code:"DD",a:"\\d{2,2}",b:function(a){return y(a.getDate())},f:function(a){return h(a)},c:function(a){return v(a)},set:function(a,b){return D(a,b)},g:function(a){return 10*a.getDate()>F(a)?1:2}},{code:"Do",a:"\\d{1,2}((th)|(nd)|(rd)|(st))",b:function(a){a=a.getDate();var b=a%10,c=a%100;return 1==b&&11!=c?a+"st":
2==b&&12!=c?a+"nd":3==b&&13!=c?a+"rd":a+"th"},f:function(a){return h(a)},c:function(a){return v(a)},set:function(a,b){return D(a,b)},g:function(a){return 10*a.getDate()>F(a)?1:2}},{code:"D",a:"\\d{1,2}",b:function(a){return a.getDate().toString()},f:function(a){return h(a)},c:function(a){return v(a)},set:function(a,b){return D(a,b)},g:function(a){return 10*a.getDate()>F(a)?1:2}},{code:"dddd",a:"(("+e.join(")|(")+"))",b:function(a){return e[a.getDay()]},f:function(a){return I(a)},c:function(a){return f(a)},
set:function(a,b){return m(a,b)},g:function(a){return 0==a.getDay()%2?2:1}},{code:"ddd",a:"(("+e.map(function(a){return a.slice(0,3)}).join(")|(")+"))",b:function(a){return e[a.getDay()].slice(0,3)},f:function(a){return I(a)},c:function(a){return f(a)},set:function(a,b){return m(a,b)},g:function(a){return 0==a.getDay()%2?2:1}},{code:"X",a:"\\d{1,}",b:function(a){return Math.floor(a.valueOf()/1E3).toString()},f:function(a){return new Date(a.valueOf()+1E3)},c:function(a){return new Date(a.valueOf()-
1E3)},set:function(a,b){var c;a:if(c=a,"ZERO_OUT"===b)c=new Date(0);else{if("string"===typeof b&&/^\d+$/.test(b))c=parseInt(b,10);else if("number"===typeof b)c=b;else{c=void 0;break a}c=new Date(1E3*c)}return c}},{code:"x",a:"\\d{1,}",b:function(a){return a.valueOf().toString()},f:function(a){return new Date(a.valueOf()+1)},c:function(a){return new Date(a.valueOf()-1)},set:function(a,b){var c;a:if(c=a,"ZERO_OUT"===b)c=new Date(0);else{if("string"===typeof b&&/^\d+$/.test(b))c=parseInt(b,10);else if("number"===
typeof b)c=b;else{c=void 0;break a}c=new Date(c)}return c}},{code:"HH",a:"\\d{2,2}",b:function(a){return y(a.getHours())},f:function(a){return r(a)},c:function(a){return x(a)},set:function(a,b){return d(a,b)},g:function(a){return 2<a.getHours()?1:2}},{code:"H",a:"\\d{1,2}",b:function(a){return a.getHours().toString()},f:function(a){return r(a)},c:function(a){return x(a)},set:function(a,b){return d(a,b)},g:function(a){return 2<a.getHours()?1:2}},{code:"hh",a:"\\d{2,2}",b:function(a){return y(N(a.getHours()))},
f:function(a){return r(a)},c:function(a){return x(a)},set:function(a,b){return k(a,b)},g:function(a){return K(a)}},{code:"h",a:"\\d{1,2}",b:function(a){return N(a.getHours()).toString()},f:function(a){return r(a)},c:function(a){return x(a)},set:function(a,b){return k(a,b)},g:function(a){return K(a)}},{code:"A",a:"((AM)|(PM))",b:function(a){return 12>a.getHours()?"AM":"PM"},f:function(a){return J(a)},c:function(a){return t(a)},set:function(a,b){return p(a,b)},g:function(){return 1}},{code:"a",a:"((am)|(pm))",
b:function(a){return 12>a.getHours()?"am":"pm"},f:function(a){return J(a)},c:function(a){return t(a)},set:function(a,b){return p(a,b)},g:function(){return 1}},{code:"mm",a:"\\d{2,2}",b:function(a){return y(a.getMinutes())},f:function(a){return q(a)},c:function(a){return u(a)},set:function(a,b){return l(a,b)},g:function(a){return 5<a.getMinutes()?1:2}},{code:"m",a:"\\d{1,2}",b:function(a){return a.getMinutes().toString()},f:function(a){return q(a)},c:function(a){return u(a)},set:function(a,b){return l(a,
b)},g:function(a){return 5<a.getMinutes()?1:2}},{code:"ss",a:"\\d{2,2}",b:function(a){return y(a.getSeconds())},f:function(a){return n(a)},c:function(a){return A(a)},set:function(a,b){return g(a,b)},g:function(a){return 5<a.getSeconds()?1:2}},{code:"s",a:"\\d{1,2}",b:function(a){return a.getSeconds().toString()},f:function(a){return n(a)},c:function(a){return A(a)},set:function(a,b){return g(a,b)},g:function(a){return 5<a.getSeconds()?1:2}},{code:"ZZ",a:"(\\+|\\-)\\d{2,2}:\\d{2,2}",b:function(a){return H(a,
!0)}},{code:"Z",a:"(\\+|\\-)\\d{4,4}",b:function(a){return H(a,!1)}}]}(),L=function(){function g(d){return new Date(d.valueOf())}var n,A,l,q,u,k,r,x;return function(){function d(d,h){"object"===typeof d?(n=d.b,l=d.f,q=d.c,u=d.set,x=d.g,A=d.a,r=void 0!==l&&void 0!==q):(k=d,A=k.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g,"\\$&"),r=!1);"boolean"===typeof h&&(r=h)}d.prototype.o=function(d){return l(g(d))};d.prototype.m=function(d){return q(g(d))};d.prototype.u=function(d){if(void 0===n)return this;
k=n(g(d));return this};d.prototype.toString=function(){return k};d.prototype.h=function(){return r};d.prototype.l=function(){return A};d.prototype.i=function(d,h){return u(g(d),h)};d.prototype.j=function(d){return void 0===x?void 0:x(g(d))};return d}()}(),P=function(){return function(){function g(){}g.s=function(n){if(void 0===n.element)throw'DATIUM: "element" option is required';console.log("oh yeah aha")};return g}()}(),Q=function(){return function(){function g(){}g.parse=function(n){function g(){0<
k.length&&(u.push(new L(k)),k="")}for(var l=0,q=!1,u=[],k="",r;l<n.length;)q||"["!==n[l]?q&&"]"===n[l]?(q=!1,l++):q?(k+=n[l],l++):O.some(function(k){var d="{"+k.code+"}";if(n.slice(l,l+d.length)===d)return g(),u.push(new L(k,!1)),r=k.code.length+2,!0;d=k.code;if(n.slice(l,l+d.length)===d)return g(),u.push(new L(k)),r=k.code.length,!0})?l+=r:(k+=n[l],l++):(q=!0,l++);g();return u};return g}()}();window.Datium=function(){return function(){function g(g){new R(g.element,"h:mma {ddd} MMM Do, YYYY");this.v(g)}
g.prototype.v=function(g){P.s(g)};return g}()}();var R=function(){function g(d){var f="";d.forEach(function(d){f+=d.l()});return new RegExp("^"+f+"$","i")}function n(){function t(){f.removeEventListener("mousedown",n);document.removeEventListener("mouseup",g);document.removeEventListener("touchstart",t)}function g(){H&&(H=!1,h=u(f.selectionStart===K?f.selectionEnd:f.selectionStart),(0<f.selectionStart||f.selectionEnd<f.value.length)&&d())}function n(){clearInterval(C);H=!0;f.setSelectionRange(void 0,
void 0);setTimeout(function(){K=f.selectionStart})}f.addEventListener("focus",function(){return k()});f.addEventListener("keydown",function(e){if(36!==e.keyCode&&35!==e.keyCode||!e.shiftKey)if(67!==e.keyCode||!e.ctrlKey)if(65!==e.keyCode||!e.ctrlKey)if(86!==e.keyCode||!e.ctrlKey)if(37!==e.keyCode&&39!==e.keyCode||!e.shiftKey){if(36===e.keyCode)h=r(),d(),e.preventDefault();else if(35===e.keyCode)h=x(),d(),e.preventDefault();else if(37===e.keyCode)h=l(),d(),e.preventDefault();else if(e.shiftKey&&9===
e.keyCode){var a=l();a!==h&&(h=a,d(),e.preventDefault())}else 39===e.keyCode?(h=q(),d(),e.preventDefault()):9===e.keyCode?(a=q(),a!==h&&(h=a,d(),e.preventDefault())):(38===e.keyCode?(a=m[h].o(v),d(a)):40===e.keyCode&&(a=m[h].m(v),d(a)),e.preventDefault());a={48:"0",96:"0",49:"1",97:"1",50:"2",98:"2",51:"3",99:"3",52:"4",100:"4",53:"5",101:"5",54:"6",102:"6",55:"7",103:"7",56:"8",104:"8",57:"9",105:"9",65:"a",66:"b",67:"c",68:"d",69:"e",70:"f",71:"g",72:"h",73:"i",74:"j",75:"k",76:"l",77:"m",78:"n",
79:"o",80:"p",81:"q",82:"r",83:"s",84:"t",85:"u",86:"v",87:"w",88:"x",89:"y",90:"z"}[e.keyCode];8===e.keyCode?(2>p.length&&(e=v.valueOf(),a=m[h].i(v,"ZERO_OUT"),a.valueOf()!==e&&d(a)),p=p.slice(0,p.length-1)):void 0!==a?p+=a:e.shiftKey||(p="");0<p.length&&(e=m[h].i(v,p),void 0!==e&&void 0!==m[h].j(e)&&p.length>=m[h].j(e)&&(h=q()),void 0===e?p=p.slice(0,p.length-1):d(e))}});f.addEventListener("paste",function(){return A()});document.addEventListener("keydown",function(e){e.shiftKey&&9===e.keyCode?
B=!0:9===e.keyCode&&(G=!0);setTimeout(function(){G=B=!1})});f.addEventListener("dragenter",function(e){return e.preventDefault()});f.addEventListener("dragover",function(e){return e.preventDefault()});f.addEventListener("drop",function(e){return e.preventDefault()});f.addEventListener("cut",function(e){return e.preventDefault()});var K,H=!1;f.addEventListener("mousedown",n);document.addEventListener("mouseup",g);document.addEventListener("touchstart",t);var y,w,C=setInterval(function(){z||0===f.selectionStart&&
f.selectionEnd===f.value.length||f.selectionStart===y&&f.selectionEnd===w||(h=u(f.selectionStart+(f.selectionEnd-f.selectionStart)/2),d());y=f.selectionStart;w=f.selectionEnd})}function A(){z=!0;var t=f.value;setTimeout(function(){if(I.test(f.value)){var h=new Date(v.valueOf()),g="";m.forEach(function(d){var t=f.value.replace(g,"").match(d.l())[0];g+=t;d.h()&&(h=d.i(h,t))});d(h)}else f.value=t;z=!1})}function l(){for(var d=h;0<=--d;)if(m[d].h())return d;return h}function q(){for(var d=h;++d<m.length;)if(m[d].h())return d;
return h}function u(d){for(var f=0,h,g,k=0;k<m.length;k++){if(m[k].h()){var l=d-f,n=d-(f+m[k].toString().length);if(0<l&&0>n)return k;l=Math.min(Math.abs(l),Math.abs(n));if(void 0==h||l<=g)h=k,g=l}f+=m[k].toString().length}return h}function k(){G?(h=r(),setTimeout(function(){d()})):B&&(h=x(),setTimeout(function(){d()}))}function r(){for(var d=0;d<m.length;d++)if(m[d].h())return d}function x(){for(var d=m.length-1;0<=d;d--)if(m[d].h())return d}function d(d){void 0===d&&(d=v);void 0!==E&&d.valueOf()<
E.valueOf()&&(d=new Date(E.valueOf()));void 0!==w&&d.valueOf()<w.valueOf()&&(d=new Date(w.valueOf()));h!==J&&(p="");J=h;v=new Date(d.valueOf());var g="";m.forEach(function(f){g+=f.u(d).toString()});f.value=g;D()}function D(){if(void 0!==h&&document.activeElement===f){for(var d=0,g=0;g<h;g++)d+=m[g].toString().length;f.setSelectionRange(d,d+m[h].toString().length)}}var h,v,m,I,f,E,w,B=!1,G=!1,z=!1,p="",J;return function(){return function(h,k,l,p){this.min=l;this.max=p;f=h;E=l;w=p;m=Q.parse(k);I=g(m);
n();f.setAttribute("spellcheck","false");d(new Date)}}()}()})();
